runtime: python37

# TESTING ONLY: keep static files fresh
default_expiration: "30s"

handlers:
- url: /admin/.*
  script: auto
  login: admin
- url: /api/.*
  script: auto
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
