runtime: python37

handlers:
- url: /bootstrap
  script: auto
  login: admin
- url: /api/.*
  script: auto
- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
